FROM alpine

ENV ALPINE_RUNIT=1

## Copy folders
COPY alpine-base/rootfs /
COPY alpine-runit/rootfs /
COPY test/alpine-runit/rootfs /

## Copy files
COPY alpine-base/install-base.sh /tmp/install-base.sh
COPY alpine-runit/install-runit.sh /tmp/install-runit.sh

## Add test user
RUN \
    addgroup -S -g "1005" "test" \
    && adduser -S -D -u "1005" -G "test" -h "/home/test" -s /bin/bash "test"

## Install
RUN \
	# Print executed commands
	set -x \
    # Update repository indexes
    && apk update \
    # Run the install script
    && sh /tmp/install-runit.sh local \
	# Clear apk's cache
	&& rm -rf /var/cache/apk/* /tmp/* /var/tmp/*

## Entrypoint
ENTRYPOINT ["/entrypoint.sh"]

## Start runit
CMD ["start"]
