FROM alpine

ENV ALPINE_BASE=1

## Copy folders
COPY alpine-base/rootfs /
COPY test/alpine-base/rootfs /

## Copy files
COPY alpine-base/install-base.sh /tmp/install-base.sh

## Add test user
RUN \
    addgroup -S -g "1005" "test" \
    && adduser -S -D -u "1005" -G "test" -h "/home/test" -s /bin/bash "test"

## Install
RUN \
	# Print executed commands
	set -x \
    # Update repository indexes
    && apk update \
    # Run the install script
    && sh /tmp/install-base.sh local \
    # install packages
    && apk add --no-cache gnupg \
	# Clear apk's cache
	&& rm -rf /var/cache/apk/* /tmp/* /var/tmp/*

## Entrypoint
ENTRYPOINT ["/entrypoint.sh"]
