FROM alpine

ENV ALPINE_RUNIT=1

## Copy files
COPY alpine-base/install-base.sh /tmp/install-base.sh
COPY alpine-runit/rootfs/entrypoint.sh /entrypoint.sh
COPY alpine-runit/install-runit.sh /tmp/install-runit.sh

## Install
RUN \
	# Print executed commands
	set -x \
    # Update repository indexes
    && apk update \
    # Run the install script
    && sh /tmp/install-runit.sh local \
	# Clear apk's cache
	&& rm -rf /var/cache/apk/* /tmp/* /var/tmp/*

## Examples
COPY alpine-base/rootfs /
COPY alpine-runit/rootfs /
COPY test/alpine-runit/rootfs /

# Make entrypoint executable
RUN chmod 0755 entrypoint.sh

## Entrypoint
ENTRYPOINT ["/entrypoint.sh", "tini", "--"]
