FROM alpine

ENV ALPINE_RUNIT=1

## dsuite user
ENV NEW_USER="dsuite"
ENV USER="dsuite"

## Copy files
COPY alpine-base/rootfs /
COPY alpine-base/install-base.sh /tmp/install-base.sh
COPY alpine-runit/rootfs /
COPY alpine-runit/install-runit.sh /tmp/install-runit.sh

## Install
RUN \
	# Print executed commands
	set -x \
    # Update repository indexes
    && apk update \
    # Run the install script
    && sh /tmp/install-runit.sh local \
	# Clear apk's cache
	&& apk-cleanup

## Examples
COPY test/alpine-runit/rootfs /

## Entrypoint
ENTRYPOINT ["/entrypoint.sh"]
