FROM alpine


## Copy files
COPY alpine-base/rootfs /
COPY alpine-base/install-base.sh /tmp/install-base.sh


## Install
RUN \
	# Print executed commands
	set -x \
    # Update repository indexes
    && apk update \
    # Run the install script
    && sh /tmp/install-base.sh \
	# Clear apk's cache
	&& apk-cleanup

## Testing
ENV TINI_VERSION v0.18.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini.asc /tini.asc
ENV GPG_KEYS="595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7"



## Entrypoint
ENTRYPOINT ["/entrypoint.sh"]
