FROM alpine

ENV ALPINE_BASE=1

## Copy files
COPY alpine-base/rootfs /
COPY alpine-base/install-base.sh /tmp/install-base.sh


## Install
RUN \
	# Print executed commands
	set -x \
    # Update repository indexes
    && apk update \
    # Run the install script
    && sh /tmp/install-base.sh \
    # intsall packages
    && apk-install gnupg \
	# Clear apk's cache
	&& apk-cleanup

## Examples
COPY tests/alpine-base/rootfs /

## Entrypoint
ENTRYPOINT ["/entrypoint.sh"]
