#!/usr/bin/env bash

# Initialisation tasks
#
# Each scripts in /etc/runit/init.d will be run before starting the services.
# This is the good place to add all you initialisation scripts

# set -e : Exit the script if any statement returns a non-true return value.
# set -u : Exit the script when using uninitialised variable.
# set -o pipefail : Check the exit code of pipeline's last command.
set -euo pipefail

# Add libraries
source /usr/local/lib/bash-logger.sh
source /usr/local/lib/persist-env.sh

#
INFO "[RUNIT] Starting ..."

# Run every scripts in /etc/runit/init.d
if [ -n "$(ls -A /etc/runit/init.d)" ]; then
    #
    INFO "[RUNIT] Running initialization scripts ..."
    # Iterate throw all script in /etc/runit/init.d/
    # and run them if the scripts are executable
    # and if runit is not stoping
    for _script in /etc/runit/init.d/*; do
        if [ -x "${_script}" ] && [ ! -e /etc/runit/stopall ]; then
            #
            DEBUG "[RUNIT] Running ${_script}"
            #
            ${_script}
            retval=$?
            #
            if [ ${retval} != 0 ]; then
                ERROR "[RUNIT] Failed to run ${_script} with return value: ${retval}"
                if [ ${FAIL_MODE} -eq 1 ]; then
                    touch /etc/runit/stopall
                    exit 100
                fi
            fi
        else
            WARNING "[RUNIT] Failed to run: ${_script}. Please chmod +x ${_script}"
        fi
    done
fi

# Create runit file:
touch /etc/runit/runit
# Create stopit file:
touch /etc/runit/stopit
chmod 0 /etc/runit/stopit

unset _script
