#!/usr/bin/env bash

# Run runit by specifying the service directory
# Must be run using exec

# set -e : Exit the script if any statement returns a non-true return value.
# set -u : Exit the script when using uninitialised variable.
# set -o pipefail : Check the exit code of pipeline's last command.
set -euo pipefail

# Add libraries
source /usr/local/lib/persist-env.sh

# Reset PATH to avoid messed up duplication
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

exec env - PATH=${PATH} \
    /sbin/runsvdir -P /etc/service
