#!/bin/sh

# Run runit by specifying the service directory
# Must be run using exec

# set -e : Exit the script if any statement returns a non-true return value.
# set -o pipefail : Check the exit code of pipeline's last command.
# set -u : Exit the script when using uninitialised variable.
set -euo pipefail

# Reset PATH to avoid messed up duplication
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Make environnement variables accessibles
[ -r /etc/envvars ] && . /etc/envvars

exec env - PATH=${PATH} \
    /sbin/runsvdir -P /etc/service
