#!/bin/sh

# Make environnement variables accessibles
[ -r /etc/envvars ] && . /etc/envvars

# Make sure http_proxy and HTTP_PROXY exists
[ -n "$http_proxy" -a -z "$HTTP_PROXY" ] && export HTTP_PROXY="$http_proxy"
[ -n "$https_proxy" -a -z "$HTTPS_PROXY" ] && export HTTPS_PROXY="$https_proxy"
[ -n "$HTTP_PROXY" -a -z "$http_proxy" ] && export http_proxy="$HTTP_PROXY"
[ -n "$HTTPS_PROXY" -a -z "$https_proxy" ] && export https_proxy="$HTTPS_PROXY"
# Make sure that proxy begin with http or https
[ -n "$http_proxy" ] && [ -z $(echo $http_proxy | grep '^http') ] && export http_proxy="http://"$http_proxy
[ -n "$HTTP_PROXY" ] && [ -z $(echo $HTTP_PROXY | grep '^http') ] && export HTTP_PROXY="http://"$HTTP_PROXY
[ -n "$https_proxy" ] && [ -z $(echo $https_proxy | grep '^http') ] && export https_proxy="https://"$https_proxy
[ -n "$HTTPS_PROXY" ] && [ -z $(echo $HTTPS_PROXY | grep '^http') ] && export HTTPS_PROXY="https://"$HTTPS_PROXY

# Save original environment variables to /etc/envvars
export > /etc/envvars

# Run every files in /etc/entrypoint.d
for _file in $(find /etc/entrypoint.d -type f -iname *.sh | sort); do
    chmod +x ${_file}
    sh ${_file}
done

# Execute script with arguments
exec tini -- /usr/local/bin/runit "${@}"
