#!/usr/bin/env bash
# shellcheck disable=SC1091

#
# Run crond
#

# set -e : Exit the script if any statement returns a non-true return value.
# set -u : Exit the script when using uninitialised variable.
set -eu

# Add libraries
source /usr/local/lib/bash-logger.sh
source /usr/local/lib/persist-env.sh

#
INFO "[RUNIT] Starting crond ..."

# Create cron log file
mkdir -p /var/log/cron
touch /var/log/cron/cron.log

# start crond
/usr/sbin/crond -b -l 2 -L /var/log/cron/cron.log
